package com.walletiq.enums;

/**
 * Represents the role of a message within a chat conversation.
 * The role is useful for maintaining conversation context when sending
 * messages to AI models or displaying chat history in the UI.</p>
 */
public enum MessageRole {

    /**
     * Message sent by the user.
     */
    USER,

    /**
     * Message generated by the AI assistant.
     */
    ASSISTANT
}