package com.walletiq.enums;

/**
 * Represents the role of a message in a conversation.
 */
public enum MessageRole {
    USER,        // Message sent by the user
    ASSISTANT    // Message generated by the AI assistant
}