package online.walletiq.dto.subscription;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(
    name = "CreateOrderResponse",
    description = "Response returned after creating a Razorpay order"
)
public record CreateOrderResponse(

    @Schema(
        description = "Unique order ID generated by Razorpay",
        example = "order_Ma8J9x7k2YpQz1"
    )
    String orderId,

    @Schema(
        description = "Amount in smallest currency unit (paise for INR). Example: 50000 = ₹500.00",
        example = "50000"
    )
    int amount,

    @Schema(
        description = "Currency of the order (ISO format)",
        example = "INR"
    )
    String currency,

    @Schema(
        description = "Razorpay public key used by frontend to initialize checkout",
        example = "rzp_test_1DP5mmOlF5G5ag"
    )
    String keyId

) {
}