# development only

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: walletiq-postgres-dev
    restart: on-failure
    environment:
      POSTGRES_DB: walletiq
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - walletiq-dev

  redis:
    image: redis:7.2-alpine
    container_name: walletiq-redis-dev
    restart: on-failure
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --requirepass strongPassword
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "strongPassword", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-dev-data:/data
    networks:
      - walletiq-dev

volumes:
  postgres-dev-data:
  redis-dev-data:

networks:
  walletiq-dev:
    driver: bridge