package com.walletiq.dto.subscription;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

@Schema(
    name = "VerifyPaymentRequest",
    description = "Request payload to verify Razorpay payment signature after successful payment"
)
public record VerifyPaymentRequest(

    @NotBlank(message = "Razorpay order ID must not be blank")
    // TODO: Set more validation once done.
    // @Size(max = 100, message = "Order ID must not exceed 100 characters")
    @Schema(
        description = "Unique order ID generated by Razorpay",
        example = "order_Ma8J9x7k2YpQz1"
    )
    String razorpayOrderId,

    @NotBlank(message = "Razorpay payment ID must not be blank")
    // @Size(max = 100, message = "Payment ID must not exceed 100 characters")
    @Schema(
        description = "Unique payment ID returned by Razorpay after transaction",
        example = "pay_Ma8K3l9ZxYpQw2"
    )
    String razorpayPaymentId,

    @NotBlank(message = "Razorpay signature must not be blank")
    // @Size(min = 10, max = 255, message = "Signature length must be between 10 and 255 characters")
    // @Pattern(regexp = "^[a-zA-Z0-9]+$", message = "Signature must be alphanumeric")
    @Schema(
        description = "HMAC SHA256 signature generated by Razorpay to verify payment authenticity",
        example = "5f3a2b1c9d8e7f6a4b3c2d1e0f9a8b7c6d5e4f3a2b1c9d8e7f6a4b3c2d1e0f9"
    )
    String razorpaySignature

) {
}