package online.walletiq.dto.chat;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Response containing the assistant's generated answer")
public record ChatQueryResponse(

    @Schema(
        description = "Answer generated by the assistant based on the user's query",
        example = "You spent ₹3,250 on food this month."
    )
    String answer

) {
}