package online.walletiq.enums;

/**
 * Represents the type of notification generated by the system.
 * Notification types help categorize alerts so the frontend can display
 * appropriate icons, messages, or priority levels.
 */
public enum NotificationType {

    /**
     * Alert when a login occurs from a new device or location.
     */
    LOGIN_ALERT,

    /**
     * Alert when a budget threshold is reached or exceeded.
     */
    BUDGET_ALERT,

    /**
     * Notification related to recurring transactions execution.
     */
    RECURRING_TRANSACTION,

    /**
     * Notification related to savings goal updates or completion.
     */
    SAVINGS_GOAL,

    /**
     * General system-level notification.
     */
    SYSTEM
}